from fastapi import FastAPI, Depends

from config import APIConfiguration
from infrastructure.open_ai.open_ai_facade_impl import OPENAIFacadeImpl
from domain.price_predictor.i_listings_model import IListingsModel
from infrastructure.price_predictor.predict_price_facade import PredictPriceFacade
from domain.models.apartment import Apartment
from domain.models.house import House
from infrastructure.price_predictor.apartment_price_predictor import ApartmentPricePredictor
from infrastructure.price_predictor.house_price_predictor import HousePricePredictor

app = FastAPI()
config = APIConfiguration()


@app.get('/house/')
async def get_house_predicted_price(house: IListingsModel = Depends(House)):
    """ Predicts the price of a house based on its features.

    Parameters:
    - house: an instance of a class implementing IListingsModel with the features of the house to predict its price.

    Returns:
    A dictionary with the predicted price and the input features used for the prediction."""
    facade = PredictPriceFacade(listing_model=house, trained_model=HousePricePredictor())
    return facade.predict()


@app.get('/apartment/')
async def get_apartment_predicted_price(apartment: IListingsModel = Depends(Apartment)):
    """ Predicts the price of an apartment based on its features.

    Parameters:
    - apartment: an instance of a class implementing IListingsModel with
     the features of the apartment to predict its price.

    Returns:
    A dictionary with the predicted price and the input features used for the prediction. """
    facade = PredictPriceFacade(listing_model=apartment, trained_model=ApartmentPricePredictor())
    return facade.predict()


@app.get('/open-ai-completion/{prompt}')
async def get_open_ai_completion(prompt: str):
    """ Obtains the response generated by OpenAI by providing a prompt.

    Parameters:
        prompt (str): The prompt for which a response is desired.

    Returns:
        dict[str, str] | None: A dictionary containing the text generated by OpenAI,
        in the format: {'text': 'text generated by OpenAI'}, or None if a response
        couldn't be obtained from OpenAI. """

    facade = OPENAIFacadeImpl(config)
    text_completion = facade.create(prompt=prompt)
    return text_completion.result
